version: 3.8
services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    networks:
      - inception_network
    restart: always
    volumes:
      - mariadb_data
  wordpress:
    build: ./requirements/wordpress/
    container_name: postgress
    networks:
      - inception_network
    volumes:
      - worldpress_data
    restart: always   

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jcardina/data
      o: bind
  worldpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jcardina/data
      o: bind

networks:
  inception_network:
    driver: bridge

#comment