services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    networks:
      - inception_network
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jcardina/data/mysql  #ricoradati di cambiare la path sulla vm
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jcardina/data/wordpress #ricordati di cambiare la path sulla vm
      o: bind

networks:
  inception_network:
    driver: bridge

#comment